work for terraform 0.14
cloudposse/terraform-aws-kms-key pull request #20
Opened 2020-12-04 18:24 UTC by dmattia

2020-12-04 20:36 UTC, joe-niland commented
@dmattia could you please update the context.tf file in the examples directory too?

2020-12-07 20:49 UTC, dmattia commented
Done 😄 

@joe-niland

2020-12-07 21:23 UTC, joe-niland commented
/test all

2020-12-07 22:46 UTC, joe-niland commented
/rebuild-readme

2020-12-07 22:47 UTC, joe-niland commented
/test all

2020-12-07 23:37 UTC, aknysh commented on context.tf
> +  source = "git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.22.0"
@dmattia 
Please use this format 
```
  source  = "cloudposse/label/null"
  version = "0.22.0"
```

we are updating all modules now.
thanks

2020-12-07 23:37 UTC, aknysh commented on examples/complete/context.tf
> +  source = "git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.22.0"
source  = "cloudposse/label/null"
version = "0.22.0"

2020-12-07 23:38 UTC, aknysh requested changes
please see comments

2020-12-08 14:36 UTC, dmattia commented
Updated the source type 👍

2020-12-08 14:50 UTC, aknysh commented
/test all

2020-12-08 16:03 UTC, aknysh commented
@dmattia  thanks!
Please fix one more issue :)  (sorry for this, we just updating all modules and all tests to the latest standards).

To fix this error 
```
not ok - check if terraform providers have explicit source locations for TF =>0.13
```

please update all the providers (in the module and in the `examples/complete` test) to use this format 

```
terraform {
  required_version = ">= 0.12.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.0"
    }
    template = {
      source  = "hashicorp/template"
      version = ">= 2.0"
    }
    local = {
      source  = "hashicorp/local"
      version = ">= 1.3"
    }
  }
}
```

2020-12-08 17:09 UTC, dmattia commented
perfect, just updated @aknysh

2020-12-08 17:13 UTC, aknysh commented
/test all

2020-12-08 17:20 UTC, aknysh commented
/test all

2020-12-08 17:35 UTC, aknysh commented
/rebuild-readme

2020-12-08 17:41 UTC, aknysh commented
/test all

2020-12-09 16:25 UTC, aknysh commented
/test all

2020-12-09 16:28 UTC, aknysh commented
/terraform-fmt

2020-12-09 16:29 UTC, aknysh commented
/test all

2020-12-09 16:33 UTC, aknysh approved these changes
thanks @dmattia

2020-12-09 16:33 UTC, merged