Terraform 0.14 upgrade
cloudposse/terraform-aws-kms-key pull request #22
Opened 2021-01-05 16:11 UTC by maximmi

## what
- Upgrade to support Terraform 0.14 and bring up to current Cloud Posse standard

## why
- Support Terraform 0.14

2021-01-07 12:20 UTC, maximmi commented
/test all

2021-02-02 14:33 UTC, evilr00t commented
Currently KMS version pinned is not supporting v0.14.15

```versions.tf line 2, in terraform:
   2:   required_version = ">= 0.12.0, < 0.14.0"

```

2021-02-04 07:14 UTC, htplbc approved these changes

2021-02-25 22:34 UTC, osterman approved these changes

2021-02-25 22:36 UTC, osterman commented on .github/workflows/validate-codeowners.yml
> -      name: "Full check of CODEOWNERS"
This seems wrong. shouldn't be deleted

2021-02-25 22:37 UTC, osterman requested changes
This seems to be introducing a regression

2021-11-12 14:25 UTC, nitrocode commented
This PR doesn't seem relevant anymore so Ill close this. Please reopen if I'm mistaken.

2021-11-12 14:25 UTC, closed without merging